In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
from sklearn import datasets

In [2]:
data=datasets.fetch_california_housing()

In [3]:
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [17]:
data.data.shape

(20640, 8)

In [4]:
x=pd.DataFrame(data.data,columns=data.feature_names)

In [5]:
x.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [6]:
y=pd.DataFrame(data.target,columns=data.target_names)

In [7]:
y.head()

MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

In [8]:
x.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

In [9]:
x.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [10]:
y.isnull().sum()

MedHouseVal    0
dtype: int64

In [3]:
x=data.data
y=data.target

In [4]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=100)

In [12]:
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.transform(xtest)


In [5]:
rf=RandomForestRegressor(100)
rf=rf.fit(xtrain,ytrain)
predictions=rf.predict(xtest)

In [6]:
predictions.shape

(4128,)

In [7]:
print(mean_squared_error(ytest,predictions))

0.24600903289790502


#K FOLD CROSS VALIDATION

In [8]:
kfold=KFold(n_splits=5,shuffle=False)

In [12]:
for train_index,test_index in kfold.split(x):
  print(f"Train is: {train_index } \n Test is \n {test_index} ")
  print("*"*20)

Train is: [ 4128  4129  4130 ... 20637 20638 20639] 
 Test is 
 [   0    1    2 ... 4125 4126 4127] 
********************
Train is: [    0     1     2 ... 20637 20638 20639] 
 Test is 
 [4128 4129 4130 ... 8253 8254 8255] 
********************
Train is: [    0     1     2 ... 20637 20638 20639] 
 Test is 
 [ 8256  8257  8258 ... 12381 12382 12383] 
********************
Train is: [    0     1     2 ... 20637 20638 20639] 
 Test is 
 [12384 12385 12386 ... 16509 16510 16511] 
********************
Train is: [    0     1     2 ... 16509 16510 16511] 
 Test is 
 [16512 16513 16514 ... 20637 20638 20639] 
********************


In [14]:
rf1=RandomForestRegressor()
error=[]

for train_index,test_index in kfold.split(x):
  xtrain,xtest=x[train_index],x[test_index]
  ytrain,ytest=y[train_index],y[test_index]

  rf1=RandomForestRegressor()
  rf1=rf1.fit(xtrain,ytrain)

  predictions=rf1.predict(xtest)
  error.append(mean_squared_error(ytest,predictions))

In [10]:
error

[0.5301379327531106,
 0.3458437292635846,
 0.37363223489973535,
 0.44324761230627135,
 0.46358479065942504]

In [11]:
sum=0
for i in error:
  sum=sum+i
print("Average error for K-Fold: ", sum/len(error))

Average error for K-Fold:  0.4312892599764254
